---
output: 
  html_document:
    theme: sandstone
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

&nbsp;
&nbsp;
&nbsp;
&nbsp;

<center> <h1>**Journal Articles**</h1> </center>

## In Prep

**Laursen, S.J.**, Fiacconi, C.M. (In prep). Retrieval outcomes predict restudy decision efficacy.

&nbsp;  

## Submitted

**Laursen, S.J.**, Powers, E., Undorf, M., & Fiacconi, C.M. (In Revision). On the importance of performance-based cues in meatcognitive monitoring.

**Laursen, S.J.**, & Risko, E.F. (Submitted). Varieties of metacognitive control: Study time and restudy decisions are not equivalent

&nbsp;  

## Forthcoming  


&nbsp;  

## Published

Churey, K.R., **Laursen, S.J.**, & Fiacconi, C.M. (2025). Do metamemory judgments impair relational encoding? *Metacognition and Learning*

**Laursen, S.J.**, & Fiacconi, C.M. (2025). Becoming fluent overnight: Long-lasting influences of perceptual learning on metamemory judgments. *Canadian Journal of Experimental Psychology*

Dimarco, D., **Laursen, S.J.**, Churey, K.R., & Fiacconi, C.M. (2025). Examining the influence of list composition on the mnemonic benefit of errorful generation. *Memory, 33*(2), 145 - 156. https://doi.org/10.1080/09658211.2024.2413159

**Laursen, S.J.**, Fiacconi, C.M. (2024). Probing the effect of perceptual (dis)fluency on metacognitive judgments. *Memory & Cognition, 52*(6), 1275 - 1298.

**Laursen, S.J.**, Sluka, D., & Fiacconi, C.M. (2024). Examining adaptations in study time allocation and restudy selection as a function of expected test format. *Metacognition and Learning*. https://doi.org/10.1007/s11409-024-09373-2

**Laursen, S.J.**, Farrell, B.C.T., & Fiacconi, C.M. (2024). On the cost and benefits of restudying: Exploring the list strength effect in self-guided learning. *Memory, 32*(2), 197-222.

**Laursen, S.J.**, Wammes, J.D., & Fiacconi, C.M. (2023). Examining the effect of expected test format and test difficulty on the frequency and mnemonic costs of mind wandering. *Quarterly Journal of Experimental Psychology*. https://doi.org/10.1177/17470218231187892 

**Laursen, S.J.**, & Fiacconi, C.M. (2021). Constraints on the use of the memorizing effort heuristic. *Metacognition and Learning, 17*(1), 1-51. https://rdcu.be/cCwtK

**Laursen, S.J.**, & Fiacconi, C.M. (2021). Examining the effect of list composition on monitoring and control processes in metamemory. *Memory & Cognition, 49*(3), 498-517. https://doi.org/10.3758/s13421-020-01107-4

Fiacconi, C.M, Mitton, E.E., **Laursen, S.J.**, & Skinner, J. (2020). Isolating the contribution of perceptual fluency to judgments of learning (JOLs): evidence for reactivity in measuring the influence of fluency. *Journal of Experimental Psychology: Learning, Memory, & Cognition, 46*(5), 926-944. https://doi.org/10.1037/xlm0000766
